version: "3.9"

services:
  it-events-app:
    container_name: it-events-app
    build:
      context: .
    image: patrykdepka/it-events-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_NAME=itevents
